# Generated by Django 4.2.4 on 2023-09-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctor_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50, null=True)),
                ('Qualifications', models.CharField(max_length=100)),
                ('Shift', models.CharField(max_length=50)),
            ],
        ),
    ]
