# Generated by Django 4.2.4 on 2023-09-03 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('Medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Mg', models.IntegerField()),
                ('Company', models.CharField(max_length=50)),
                ('Available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Member_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Room_no', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=50, null=True)),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('Religion', models.CharField(max_length=50)),
                ('Account_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('Nurse_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Password', models.CharField(max_length=50, null=True)),
                ('Qualifications', models.CharField(max_length=50)),
                ('Shift', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCheckupSchedule',
            fields=[
                ('Special_Checkup_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='residents.checkupitem')),
                ('Date', models.DateField()),
                ('Frequency', models.PositiveIntegerField()),
                ('Completed', models.BooleanField(default=False)),
                ('Doctor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('Member_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.member')),
                ('Nurse_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentMedCond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cond_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.medcond')),
                ('Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberAppoint',
            fields=[
                ('App_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.member')),
                ('Nurse_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.nurse')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='Assigned_nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.nurse'),
        ),
        migrations.CreateModel(
            name='MedicineChart',
            fields=[
                ('Chart_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.member')),
            ],
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.CharField(max_length=50)),
                ('Quantity', models.CharField(max_length=20)),
                ('Chart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.medicinechart')),
                ('Medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentCond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Risk_rate', models.IntegerField()),
                ('Member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.member')),
            ],
        ),
        migrations.CreateModel(
            name='CheckupSchedule',
            fields=[
                ('Checkup_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='residents.checkupitem')),
                ('Date', models.DateField()),
                ('Completed', models.BooleanField(default=False)),
                ('Doctor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('Member_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.member')),
                ('Nurse_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.nurse')),
            ],
        ),
    ]
