# Generated by Django 4.2.4 on 2023-09-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkupschedule',
            old_name='Checkup_id',
            new_name='Checkup_Id',
        ),
        migrations.RenameField(
            model_name='medicinechart',
            old_name='Member_id',
            new_name='Member_ID',
        ),
    ]
