# Generated by Django 4.2.4 on 2023-09-04 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0002_rename_checkup_id_checkupschedule_checkup_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkupschedule',
            old_name='Doctor_Id',
            new_name='Doctor_ID',
        ),
        migrations.RenameField(
            model_name='specialcheckupschedule',
            old_name='Doctor_Id',
            new_name='Doctor_ID',
        ),
    ]
