# Generated by Django 4.2.4 on 2023-09-04 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0003_rename_doctor_id_checkupschedule_doctor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberNurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nurse_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.nurse')),
                ('Room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.member')),
            ],
            options={
                'unique_together': {('Room_no', 'Nurse_ID')},
            },
        ),
    ]
