# Generated by Django 4.2.4 on 2023-09-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0004_membernurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosage',
            name='Time',
        ),
        migrations.AddField(
            model_name='checkupschedule',
            name='Exact_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='checkupschedule',
            name='Risk_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dosage',
            name='Exact_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='specialcheckupschedule',
            name='Exact_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='specialcheckupschedule',
            name='Risk_rate',
            field=models.IntegerField(default=0),
        ),
    ]
