# Generated by Django 4.2.4 on 2023-09-06 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0005_remove_dosage_time_checkupschedule_exact_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCheckupItem',
            fields=[
                ('Special_Checkup_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Blood_Pressure', models.CharField(max_length=20)),
                ('Sugar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Heartrate', models.IntegerField()),
                ('Special_schedule_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.specialcheckupschedule')),
            ],
        ),
    ]
