# Generated by Django 4.2.4 on 2023-09-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0006_specialcheckupitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Risk_rate',
            field=models.IntegerField(default=0),
        ),
    ]
