# Generated by Django 4.2.4 on 2023-09-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0007_member_risk_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Risk_rate',
            new_name='riskrate',
        ),
    ]
