# Generated by Django 4.2.4 on 2023-09-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0008_rename_risk_rate_member_riskrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialCheckupItem',
        ),
    ]
