# Generated by Django 4.2.4 on 2023-09-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('nurses', '0009_delete_specialcheckupitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCheckupScheduletwo',
            fields=[
                ('Special_Checkup_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Frequency', models.PositiveIntegerField()),
                ('Completed', models.BooleanField(default=False)),
                ('Exact_time', models.TimeField(default='09:00:00')),
                ('Risk_rate', models.IntegerField(default=0)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('Member_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.member')),
                ('Nurse_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCheckupItem',
            fields=[
                ('Special_Checkup_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Blood_Pressure', models.CharField(max_length=20)),
                ('Sugar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Heartrate', models.IntegerField()),
                ('Schedule_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurses.specialcheckupscheduletwo')),
            ],
        ),
    ]
