# Generated by Django 4.2.4 on 2023-09-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('nurses', '0010_specialcheckupscheduletwo_specialcheckupitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Assigned_doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
