# Generated by Django 4.2.4 on 2023-09-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0011_member_assigned_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialcheckupitem',
            old_name='Special_Checkup_Id',
            new_name='Special_Checkup_Item_Id',
        ),
    ]
